org: danbart
app: reddit-scraper


service: cloud-scraper
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  timeout: 900
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action: "*"
      Resource: "*"

package:
 excludeDevDependencies: false
 exclude: #so that this huge file is not uploaded to lambda
  - node_modules/**
  - venv/**

custom:
  pythonRequirements: #to include dependencies
    dockerizePip: true

plugins:
  - serverless-python-requirements
  - serverless-plugin-include-dependencies

functions:
  dailyScraper:
    handler: handler.dailyScraper
    events:
     - schedule: cron(0 20 ? * * *)